# Generated by Django 2.2.19 on 2024-07-23 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type_beer', models.CharField(max_length=20)),
                ('provider', models.CharField(max_length=100)),
                ('manufacturer', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('density', models.TextField()),
                ('fortress', models.TextField()),
                ('color', models.TextField()),
                ('bitterness', models.TextField()),
                ('fortress_in_procent', models.TextField()),
                ('taste', models.TextField()),
                ('date_publication', models.DateField(auto_now_add=True)),
                ('photo', models.ImageField(upload_to='')),
            ],
        ),
    ]
