# Generated by Django 5.0.7 on 2024-08-01 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_manufacturer', models.CharField(max_length=100, verbose_name='Название производителя')),
                ('country', models.CharField(max_length=100, verbose_name='Страна')),
                ('city', models.CharField(max_length=50, verbose_name='Город')),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_provider', models.CharField(max_length=100, verbose_name='Название компании')),
                ('INN', models.CharField(max_length=15, verbose_name='ИНН')),
                ('number_of_agreement', models.CharField(max_length=50, verbose_name='Номер договора')),
                ('active', models.BooleanField(default=False, verbose_name='Статус поставщика')),
            ],
        ),
        migrations.CreateModel(
            name='Type_beer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=1, verbose_name='Ключ')),
                ('type', models.CharField(max_length=30, verbose_name='Тип пива')),
            ],
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=30, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=30, verbose_name='Имя')),
                ('otchestvo', models.CharField(max_length=30, verbose_name='Отчество')),
                ('job_title', models.CharField(max_length=30, verbose_name='Должность')),
                ('phone', models.CharField(max_length=14, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Contacts', to='beer_menu.provider')),
            ],
        ),
        migrations.CreateModel(
            name='Beer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('density', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=1, verbose_name='Плотность от 1 до 5')),
                ('fortress', models.TextField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=1, verbose_name='Крепость от 1 до 5')),
                ('color', models.TextField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=1, verbose_name='Цвет от 1 до 5')),
                ('bitterness', models.TextField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=1, verbose_name='Горечь от 1 до 5')),
                ('alcohol', models.TextField(verbose_name='Алкоголь в %')),
                ('taste', models.TextField(verbose_name='Описание вкуса')),
                ('photo', models.ImageField(upload_to='', verbose_name='Фото')),
                ('active', models.BooleanField(default=False, verbose_name='В наличии')),
                ('manufacturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Manufacturers', to='beer_menu.manufacturer')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beers', to='beer_menu.provider')),
                ('type_beer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='type_beer', to='beer_menu.type_beer')),
            ],
        ),
    ]
