# Generated by Django 2.2.19 on 2024-07-23 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beer_menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='beer',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
