# Generated by Django 2.2.19 on 2024-07-23 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beer_menu', '0002_beer_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beer',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='beer',
            name='bitterness',
            field=models.TextField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=1, verbose_name='Горечь от 1 до 5'),
        ),
        migrations.AlterField(
            model_name='beer',
            name='color',
            field=models.TextField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=1, verbose_name='Цвет от 1 до 5'),
        ),
        migrations.AlterField(
            model_name='beer',
            name='date_publication',
            field=models.DateField(auto_now_add=True, verbose_name='дата создания'),
        ),
        migrations.AlterField(
            model_name='beer',
            name='density',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=1, verbose_name='Плотность от 1 до 5'),
        ),
        migrations.AlterField(
            model_name='beer',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='beer',
            name='fortress',
            field=models.TextField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=1, verbose_name='Крепость от 1 до 5'),
        ),
        migrations.AlterField(
            model_name='beer',
            name='fortress_in_procent',
            field=models.TextField(verbose_name='Крепость в %'),
        ),
        migrations.AlterField(
            model_name='beer',
            name='manufacturer',
            field=models.CharField(max_length=100, verbose_name='Производитель'),
        ),
        migrations.AlterField(
            model_name='beer',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='beer',
            name='photo',
            field=models.ImageField(upload_to='', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='beer',
            name='provider',
            field=models.CharField(max_length=100, verbose_name='Поставщик'),
        ),
        migrations.AlterField(
            model_name='beer',
            name='taste',
            field=models.TextField(verbose_name='Описание вкуса'),
        ),
        migrations.AlterField(
            model_name='beer',
            name='type_beer',
            field=models.CharField(max_length=20, verbose_name='Тип пива'),
        ),
    ]
