# Generated by Django 2.2.19 on 2024-07-23 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beer_menu', '0003_auto_20240723_2312'),
    ]

    operations = [
        migrations.RenameField(
            model_name='beer',
            old_name='fortress_in_procent',
            new_name='alcohol',
        ),
    ]
