# Generated by Django 2.2.19 on 2024-07-23 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beer_menu', '0005_auto_20240723_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beer',
            name='active',
            field=models.BooleanField(default=False, verbose_name='В наличии'),
        ),
    ]
