# Generated by Django 2.2.19 on 2024-07-23 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beer_menu', '0006_auto_20240723_2323'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_Manufacturer', models.CharField(max_length=100, verbose_name='Название производителя')),
                ('country', models.CharField(max_length=100, verbose_name='Страна')),
                ('city', models.CharField(max_length=50, verbose_name='Город')),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_provider', models.CharField(max_length=100, verbose_name='Название компании')),
                ('INN', models.CharField(max_length=10, verbose_name='ИНН')),
                ('number_of_agreement', models.CharField(max_length=50, verbose_name='Номер договора')),
            ],
        ),
        migrations.CreateModel(
            name='Type_Beer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
