# Generated by Django 2.2.19 on 2024-07-23 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beer_menu', '0007_manufacturer_provider_type_beer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manufacturer',
            old_name='name_Manufacturer',
            new_name='name_manufacturer',
        ),
    ]
