# Generated by Django 2.2.19 on 2024-07-23 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beer_menu', '0008_auto_20240723_2357'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Type_Beer',
        ),
        migrations.AlterField(
            model_name='beer',
            name='type_beer',
            field=models.CharField(choices=[('L', 'Лагер'), ('B', 'обычное'), ('K', 'Крафтовое'), ('4', '4'), ('5', '5')], max_length=1, verbose_name='Тип пива'),
        ),
    ]
