# Generated by Django 2.2.19 on 2024-07-25 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beer_menu', '0009_auto_20240724_0003'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type_beer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=1, verbose_name='Ключ')),
                ('type', models.CharField(max_length=30, verbose_name='Тип пива')),
            ],
        ),
        migrations.AddField(
            model_name='provider',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Статус поставщика'),
        ),
        migrations.AlterField(
            model_name='beer',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Manufacturers', to='beer_menu.Manufacturer', verbose_name='Производитель'),
        ),
        migrations.AlterField(
            model_name='beer',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beers', to='beer_menu.Provider', verbose_name='Поставщик'),
        ),
        migrations.AlterField(
            model_name='beer',
            name='type_beer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_beer', to='beer_menu.Type_beer'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='INN',
            field=models.CharField(max_length=15, verbose_name='ИНН'),
        ),
    ]
