# Generated by Django 5.0.7 on 2024-07-31 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beer_menu', '0010_auto_20240725_2321'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('surname', models.CharField(max_length=30, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=30, verbose_name='Имя')),
                ('otchestvo', models.CharField(max_length=30, verbose_name='Отчество')),
                ('job_title', models.CharField(max_length=30, verbose_name='Должность')),
                ('phone', models.CharField(max_length=14, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта')),
            ],
        ),
        migrations.RemoveField(
            model_name='beer',
            name='date_publication',
        ),
        migrations.AlterField(
            model_name='beer',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='provider',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='type_beer',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='provider',
            name='contact',
            field=models.ForeignKey(default='null', on_delete=django.db.models.deletion.CASCADE, related_name='Providers', to='beer_menu.contacts', verbose_name='Контакт'),
        ),
    ]
