# Generated by Django 5.0.7 on 2024-07-31 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beer_menu', '0011_contacts_remove_beer_date_publication_alter_beer_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='contact',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, related_name='Providers', to='beer_menu.contacts', verbose_name='Контакт'),
        ),
    ]
