# Generated by Django 5.0.7 on 2024-08-01 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beer_menu', '0012_alter_provider_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='contact',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='beer_menu.contacts'),
        ),
    ]
