# Generated by Django 5.0.7 on 2024-08-01 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beer_menu', '0013_alter_provider_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beer',
            name='manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Manufacturers', to='beer_menu.manufacturer'),
        ),
        migrations.AlterField(
            model_name='beer',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beers', to='beer_menu.provider'),
        ),
        migrations.AlterField(
            model_name='beer',
            name='type_beer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='type_beer', to='beer_menu.type_beer'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Provider', to='beer_menu.contacts'),
        ),
    ]
